# Generated by Django 4.0.1 on 2022-01-31 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_product_delete_shop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Cateogy', 'verbose_name_plural': 'Categories'},
        ),
    ]
