# Generated by Django 4.0.2 on 2022-02-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, upload_to='C:\\Diplom1\\django-react-todoApp\\backend\\media'),
        ),
    ]
