# Generated by Django 4.0.2 on 2022-02-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_product_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='externalURL',
            field=models.URLField(blank=True),
        ),
    ]
