# Generated by Django 4.0.2 on 2022-02-02 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_product_externalurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='externalURL',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category'),
        ),
    ]
