# Generated by Django 4.0.2 on 2022-02-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_remove_product_externalurl_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media_cdn'),
        ),
    ]
